# Generated by Django 4.1.1 on 2022-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('dob', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=150)),
                ('number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
