# Generated by Django 4.1.1 on 2022-12-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='number',
        ),
    ]
