# Generated by Django 4.1.1 on 2022-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('artist', models.CharField(max_length=50)),
                ('album', models.CharField(default='SINGLE', max_length=8)),
                ('genere', models.CharField(max_length=30)),
                ('plays', models.IntegerField(default=547809, max_length=12)),
                ('length', models.IntegerField(max_length=8)),
            ],
        ),
    ]
