# Generated by Django 4.1.1 on 2022-12-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_song_img_song_song_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('monthly_listeners', models.IntegerField(default=48494894)),
                ('artist_img', models.ImageField(default='', upload_to='song/media')),
                ('about_img', models.ImageField(default='', upload_to='song/media')),
            ],
        ),
    ]
