# Generated by Django 4.1.1 on 2022-12-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_artist_about_alter_artist_about_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='SINGLE', max_length=30),
        ),
    ]
