# Generated by Django 4.1.1 on 2022-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='length',
        ),
        migrations.AlterField(
            model_name='song',
            name='plays',
            field=models.IntegerField(default=547809),
        ),
    ]
