# Generated by Django 4.1.1 on 2022-12-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='about',
            field=models.CharField(default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='about_img',
            field=models.ImageField(default='', upload_to='song/media/artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_img',
            field=models.ImageField(default='', upload_to='song/media/artist'),
        ),
    ]
