# Generated by Django 5.0.4 on 2024-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_remove_artist_about_image_remove_artist_artist_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='about_img',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_img',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_img',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_source',
        ),
        migrations.AddField(
            model_name='artist',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_about/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='firebase_about_image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='firebase_artist_image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='firebase_image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='firebase_mp3_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='music_images/'),
        ),
        migrations.AddField(
            model_name='song',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
