# Generated by Django 4.1.1 on 2022-12-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userinfo_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
