# Generated by Django 4.1.1 on 2022-12-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
